common:
  vpc_name: RancherVPC
  vpc_subnets:
    - 10.10.0.0/24
    - 10.10.1.0/24
    - 10.10.2.0/24
  vpc_cidr: 10.10.0.0/16

  ami_name: rancheros-v0.5.0-hvm-1
  instance_type: t2.micro
  ssh_key_name: id_rsa

platform:
  dns_zone_name: openhr.co.uk
  ssl_cert_arn: arn:aws:acm:eu-west-1:592423029085:certificate/00b47e6f-698b-4bb8-9089-0bec9e6e2de7